// Build: generate dist/validators.mjs from schema/*.json, then self-check it
// against schema/samples.json. Usage: node scripts/build.mjs [--schema-dir d] [--out f]
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, join, basename } from "node:path";
import { pathToFileURL } from "node:url";

const args = process.argv.slice(2);
const opt = (name, dflt) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : dflt; };
const schemaDir = resolve(opt("--schema-dir", "schema"));
const outFile = resolve(opt("--out", "dist/validators.mjs"));
const log = (level, msg) => console.log(`${level}: ${msg}`);

const TYPE_CHECKS = {
  string: "(v) => typeof v === \"string\"",
  integer: "(v) => Number.isInteger(v)",
  number: "(v) => typeof v === \"number\" && Number.isFinite(v)",
  boolean: "(v) => typeof v === \"boolean\"",
};

log("info", "build started");
log("debug", `resolved schema dir ${schemaDir}`);
log("debug", `resolved output ${outFile}`);
const files = readdirSync(schemaDir).filter((f) => f.endsWith(".json") && f !== "samples.json").sort();
log("info", `found ${files.length} schema files`);

let schemaErrors = 0;
const parts = [];
const names = [];
for (const file of files) {
  const rel = `${basename(schemaDir)}/${file}`;
  log("info", `reading ${rel}`);
  const schema = JSON.parse(readFileSync(join(schemaDir, file), "utf8"));
  names.push(schema.name);
  const fieldParts = [];
  for (const [field, spec] of Object.entries(schema.fields)) {
    log("debug", `field ${schema.name}.${field}: type=${JSON.stringify(spec.type)}`);
    if (!spec.description) log("warn", `${rel}#${field}: missing description (docs will be empty)`);
    if (spec.format) log("warn", `${rel}#${field}: 'format' is deprecated and ignored`);
    let check = TYPE_CHECKS[spec.type];
    if (!check) {
      schemaErrors++;
      log("error", `${rel}#${field}: unknown type ${JSON.stringify(spec.type)}, emitting a validator that rejects everything`);
      check = "() => false";
    }
    fieldParts.push(`    ${JSON.stringify(field)}: ${check},`);
  }
  parts.push(`  ${JSON.stringify(schema.name)}: {\n${fieldParts.join("\n")}\n  },`);
  log("info", `docs: generating docs/${schema.name}.md`);
  for (const [field, spec] of Object.entries(schema.fields)) {
    if (!spec.description) log("warn", `docs: ${schema.name}.${field} undocumented`);
  }
}
const out = `// generated by scripts/build.mjs, do not edit\nexport const validators = {\n${parts.join("\n")}\n};\nexport function validate(schema, record) {\n  const v = validators[schema];\n  if (!v) return false;\n  return Object.keys(v).every((k) => k in record && v[k](record[k]));\n}\n`;
mkdirSync(resolve(outFile, ".."), { recursive: true });
writeFileSync(outFile, out);
let count = 0; for (const p of parts) count += (p.match(/\n/g) || []).length - 1;
log("info", `wrote ${outFile} (${count} validators)`);

log("info", "self-check started");
const { validators, validate } = await import(pathToFileURL(outFile).href + `?t=${Date.now()}`);
const samples = JSON.parse(readFileSync(join(schemaDir, "samples.json"), "utf8"));
let failed = 0, passed = 0;
for (const [schema, fields] of Object.entries(samples)) {
  for (const [field, cases] of Object.entries(fields)) {
    for (const [value, expected] of cases) {
      const got = field === "__records" ? validate(schema, value) : validators[schema][field](value);
      const shown = field === "__records" ? `record ${value.id ?? value.sku ?? value.line1}` : `${field}(${JSON.stringify(value)})`;
      log("debug", `evaluating ${schema}.${shown}`);
      if (got === expected) { passed++; log("check", `${schema}.${shown} expected ${expected}: ok`); }
      else { failed++; log("check", `${schema}.${shown} expected ${expected}: FAILED (got ${got})`); }
    }
  }
}
log("info", `self-check: ${passed} ok, ${failed} failed`);
if (failed > 0 || schemaErrors > 0) {
  log("fatal", `build failed: ${failed} checks failed, ${schemaErrors} schema errors`);
  process.exit(1);
}
log("info", `build ok: ${count} validators for ${names.join(", ")}`);
